### ISSUE TITLE
Allow registering mysterious conversion recipes

### ISSUE THREAD

**Issue by PandaBoy444** [jaredlll08/CreateTweaker#17]
Just to register something as a mysterious conversion as I like the concept, the actual recipe would be something that I add with events and such and thus doesn't go into JEI normally. I like how create does this coz there are tooltips to let you know how to make it but also in JEI where most people navigate recipes you are exposed to the fact that the recipe is not usual.

**Comment by jaredlll08** [comment]
This isn't possible, the recipes are hardcoded and can't even be added via JSON (or a mod).

There are some plans for JEITweaker to do something similar (show recipes for "concepts" that users would then add via events), but that is nothing more than just an idea at the moment.

**Comment by PandaBoy444** [comment]
There is no way to register it like they do in JEI? it's just the jei thing anyhow. I know the recipes themselves can't be recreated. Even if you add something similar to jeit it wouldn't display on the same tab which is desirable in my case. How do they add things to that jei tab?

**Comment by jaredlll08** [comment]
> There is no way to register it like they do in JEI?

Nope.

Create calls this method to provide JEI with it's recipes.

https://github.com/Creators-of-Create/Create/blob/mc1.16/dev/src/main/java/com/simibubi/create/compat/jei/category/MysteriousItemConversionCategory.java#L21-L28

The issue is, every time that method is called, a ***new*** list of recipes is made, so I can't even add to it.
